name: Sort and Format JSON

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  sort-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install json-sort-cli prettier --global

      - name: Sort and Format JSON
        run: |
          find . -name "*.json" -print0 | xargs -0 -I {} json-sort -k name {} > temp && mv temp {}
          prettier --write "**/*.json"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-sort and format JSON"
          git push
