name: Format WhatsMyName Dataset

on:
  workflow_run:
    workflows: ["Validate WhatsMyName Dataset"]
    types:
      - completed
  push:
    paths:
      - 'wmn-data.json'
      - 'wmn-data-schema.json'

jobs:
  wmn-format-dataset:
    name: Format WhatsMyName Dataset
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rich

      - name: Run dataset formatting
        run: python scripts/wmn_format_json.py

      - name: Commit changes if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add wmn-data.json wmn-data-schema.json
          git diff --cached --quiet || git commit -m "chore: auto-sort and format JSON files"
          git push
